[tool.poetry]
name = "pyobs-sbig"
version = "0.14.0"
description = "pyobs module for SBIG cameras"
authors = ["Tim-Oliver Husser <thusser@uni-goettingen.de>"]
license = "MIT"
build = 'build.py'

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.21"
astropy = "^4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0", "Cython>=0.29.0", "numpy>=1.21.0"]
build-backend = "poetry.core.masonry.api"
